# Server
server.port=${PORT:8080}

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://gondola.proxy.rlwy.net:25356/bootcamp_project_db?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:kTTcUNwgEIQnPqxqZQGbVUsOiWUgUxkA}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Logging
logging.level.root=INFO
logging.level.com.bootcamp=DEBUG
logging.pattern.console=%d{HH:mm:ss} %-5level [%logger{20}] - %msg%n

# CORS
bootcamp.cors.allowed-origins=http://localhost:5173

# Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

name=ganesh
