# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/bootcamp_project_db
spring.datasource.username=bootcamp_app_user
spring.datasource.password=ChangeMe123!
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Logging
logging.level.root=INFO
logging.level.com.bootcamp=DEBUG
logging.pattern.console=%d{HH:mm:ss} %-5level [%logger{20}] - %msg%n

# CORS
bootcamp.cors.allowed-origins=http://localhost:5173

# Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

name=ganesh
